---
users_groups:
- { name: sw_dev, gid: 3100 }

users:
- { name: ci_bot, uid: 1600 }
- name: daekyeong
  uid: 2036
  groups: [ sw_dev ]
  admin: true
  sudo: true
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOidKD1u9BAe4OW3NQ/V7UEU+0lBpFS5sZ2gZ3d1XMwP daekyeong@daekyeongkimrebellionsai.local
  ldap_username: daekyeong.kim
- name: jinmoo
  uid: 2052
  groups: [ sw_dev ]
  admin: true
  sudo: true
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHg4c6RHHlEeeAZhRWzo/ggsmBbsXx+NWGDGbHIqRxCY jinmoo_seok@NO-202506-005.local
  ldap_username: jinmoo_seok
- name: jaebin
  uid: 2054
  groups: [ sw_dev ]
  admin: true
  sudo: true
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHCYiln3M18HgbsYlrP4/t3cBb+A/Vrpe+mKGvh/due5 jaebin@NO-202509-002.local
  ldap_username: jaebin
- name: jiwoo
  uid: 2038
  groups: [ sw_dev ]
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlnMN2WynW4ApHOmbnsNFdcAV+KQ7dl085bIyDsOdDtB1L27hs6l/F7ykdIYGJuc+S0GOo58ZCiag8pIQtTC1D3gjVVet5E9EjlN4IwySwWLCn+77W6XntXOgeeVQ5OqC1vR6jyudGsf+tieQSZLS4EgtgwGpfKCtlA6J2+nYoZavxIZME4aCunDYuUY5dTw62fFVOk+qGDXfm4IrWq1T8KG9Q/gPaVVibM6eBz8/uCnwrPYf7x3JoBwl+RjUx12D9dg1VJUYu4NodTyZpUNf4BNygP5pluMM6A1bE2fd9ChldMzXz0pbgNWy7juUx12u0ohNh5tXf+FrMCBnu2pvt53rNLE1+5Bbwk1f699wcmrYkmye6qWXO7AW+cZ5t9tzi+qR6xMarW/yk2veTgPxvDahGXgN9A6dVFR+C50DZHtHd4rDdQgMhM7Q51jNcyn70wCeWO5GMJsOpbNUEKMAa4dK1y9hiXH19HHF0b0Z9mJ5MmU5gdEuLlCkAyu+GGts= jiwoopark@Jiwooui-MacBookPro.local
  ldap_username: jiwoo.park
- name: scottlee
  uid: 2039
  groups: [ sw_dev ]
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnt6WVb62+zVH97QQ7H2tAVONDD+zQeWH4jRbrtN0Mq8ktkN9mwhipDhVdNKkye+o0zDMgJeBXBjWx2D5DCLRxihjXWqi/shoTY/zxsXtNXFMMLDDcfMdfZ951SyE2CnFHO4+rlGfOxsJRFxJSwX1ZGUl+TrFHB3yojyK4TUdEcWULbzx/DLN6N8O2GqB/zV+WHBysTSa5WKP58LgE2MIUVVDf1+yu0qLs88FRViOR6A8mLdJomUSwEmVxqi+5kPVSvluUrhEJZgArXVJGFmIrIpab4JdNbWc5dLfOcjsHuKzKgS6q/Y8UujOgo1FsK1lTmcClBzMJ08Homs7B+crNQJK+ioVWoxJiSzxgo7uJi6E3dLo6ZqxTYjWhUErZ+zqrKk1Y8vlOq4dLscKdos64dm22Mv6wY+12avG/G/LXpI/4jvc9vroduHLhtDCMFmhYZW84msvDv012PSNXBAJJ/nDWv46NhmrIwo7vtN5ZX8B05IK6nKy2vAcCfSDHo0s= scottlee@Scotts-MacBook-Pro.local
  ldap_username: scott.lee
- name: jaehwang.jung
  uid: 2049
  groups: [ sw_dev ]
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDsLioXZtkvD9jBzpSTp/QuMUC38EGsaPMpPw8UzWPkq jjh@NO-202503-002
  ldap_username: jaehwang.jung
- name: chanheo
  uid: 2040
  groups: [ sw_dev ]
  ldap_username: chan.heo
- name: hongseok
  uid: 2028
  groups: [ sw_dev ]
  ldap_username: hongseok
- name: jindol21
  uid: 2042
  groups: [ sw_dev ]
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPzH+JBMJhQT/YNbIdI1Fkx19B3q3aOHJkRn/hpYTd/e jindol21@rebellions.ai
  ldap_username: jindol21
- name: jongwonlee
  uid: 2031
  groups: [ sw_dev ]
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD3TJ+/3uCMjKSqzCg/+GE7eMws9LIwsZb5O9N9qdeYH6swr0krU3Hkfban0EMW1S8RIbgbZrZnfQ+prp6PvNxgk270Yp/dic2eNwwQMWvsUJPYZ3JaA+cKM2CR4UME6HC4/3nWyYAqbf7kHKWx38o1gzrx5rU1FiG9DB0NxLu9Mpe4MEj3iLGsz2DVeCPO3vrD5i1bzaLzaRTyjHO6wHjG8+ykjQgRYZ1GauKF0Qb5tog3Pbars1wTUJNk/LJFY2/wpxZVDhQuEAq6RnbS1gksk/Gpb4+gxpBtpJnsPba1lF7iZW8o5bUMWTjZX+Sx8iqhZKwJ5zf91ehCBsoWxFbfxR3XgBUlNnsFFE0Y1o5I3eCSmQ7ARKBRSJCQZjCF8/Rs20Ga7mQ5NaZQeDcmdCDm7fqnIteMR3/aeaZrcS8BrcDS45Pl24xBynfmMtmF7PJrA3PtSB9gETixDmGqgqGodLh6b3yE4jXV1xOy2ElQwcwKokbgcW8fygKB9KTmTUGxxGzPshFHnsrm/A9tIxQXhdEaVENrLhhtdXnVaCKvCXurhqlQ/6phnIIuS3TITcgrRlnKZJ7GN2d+kZODuOabVusfkmF7o+DMCmgng+fSNoYjcIGsWvE21hmRxrCjh1yH8BnkM70VaTqP6pNsHesDuyfdAu8I/kjL0jvTeeK5jQ== jongwon@Jongwonui-MacBookPro.local
  ldap_username: jongwon.lee
- name: minwook
  uid: 2029
  groups: [ sw_dev ]
  ldap_username: minwook.ahn
- name: rebel-clee
  uid: 2035
  groups: [ sw_dev ]
  ldap_username: clee
- name: seungchul
  uid: 2041
  groups: [ sw_dev ]
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINzCkdzaAPYe0WNgyOyV14gqZlaBcLbi6zkZSLTaUC0y seungchul.han@rebellions.ai
  ldap_username: seungchul.han
- name: wonsubkim
  uid: 2030
  groups: [ sw_dev ]
  ldap_username: subang0
- name: ykchoi
  uid: 2032
  groups: [ sw_dev ]
  ldap_username: youngkyu.choi
- name: sjlee
  uid: 2055
  groups: [ sw_dev ]
  ldap_username: sjlee
